### ISSUE TITLE
Tutorial example fails on real Sapphire mixer

### ISSUE THREAD

**Issue by fredrikbergholtz-sr** [Lawo/ember-plus-sharp#28]
I started going through the tutorial here http://lawo.github.io/ember-plus-sharp/html/427fadff-8d32-472e-83d1-3ceaf705ae51.htm and it appears to work when I connect to the TinyEmberPlus dummy but when I try to direct the same code to a real Sapphire mixer, I get the following exception:
```
System.TimeoutException was unhandled by user code
  HResult=-2146233083
  Message=The provider failed to send the children for the element with the path /Sapphire.
  Source=Lawo.EmberPlusSharp
  StackTrace:
       vid Lawo.EmberPlusSharp.Model.Consumer`1.<RetrieveChildrenAsync>d__34.MoveNext() i C:\Storage\Development\Libraries\ember-plus-sharp-master\Lawo.EmberPlusSharp\Model\Consumer`1.cs:rad 279
    --- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
       vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       vid System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       vid Lawo.EmberPlusSharp.Model.Consumer`1.<CreateAsync>d__4.MoveNext() i C:\Storage\Development\Libraries\ember-plus-sharp-master\Lawo.EmberPlusSharp\Model\Consumer`1.cs:rad 118
    --- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
       vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       vid System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       vid Lawo_EmberPlusSharp_Test.Model.DataService.<connect>d__5.MoveNext() i C:\SVN\metodutv\Lawo-EmberPlusSharp-Test\src\Lawo-EmberPlusSharp-Test\Model\DataService.cs:rad 43
  InnerException: 
```
The Sapphire is configured to be an Ember+ provider, connecting with the EmberPlusView tool works fine.

What could I be doing wrong?

**Comment by andreashuber-lawo** [comment]
I assume you mean the example on [page 4](http://lawo.github.io/ember-plus-sharp/html/f6285c3c-ef54-453e-90ad-5546ec1a7a1d.htm)?

If so, please try increasing the timeout by calling the following overloads instead of the ones used in the tutorial:

1. [Consumer.Consumer](http://lawo.github.io/ember-plus-sharp/html/3CBE950.htm) (default: 10000)
2. [S101Client.S101Client](http://lawo.github.io/ember-plus-sharp/html/7345C981.htm) (default: 3000)

It's usually sufficient to only increase the first timeout, but depending on the provider it's sometimes also necessary to increase the second one.

**Comment by fredrikbergholtz-sr** [comment]
Yes, page 4. Unfortunately, increasing the timeouts does not help. I compared the traffic from the test program with the traffic from EmberPlusView and see differences. When using EmberPlusView, I first see a query and a response with the top node named "Sapphire". After that I see another query with the exact same response. Finally I see a third query and the response lists all the child nodes of "Sapphire".

With my test application I see a query, this query is quite different from the corresponding one from EmberTreeView, the response, containing the top node is identical though. After that response I see another query, again different from the other example. After this, the application sends another message (8 bytes data) to which the Sapphire responds with a short message (9 bytes data). These short messages are sent continously from here on but I never see the response to the second query. 

So, I guess that the time out is correct, the question is why the Sapphire doesn't respond to this particular query.

**Comment by andreashuber-lawo** [comment]
> So, I guess that the time out is correct, the question is why the Sapphire doesn't respond to this particular query.

Good question, could you please either use [Glow Analyzer Proxy](http://lawo.github.io/ember-plus-sharp/html/4afc50e6-0e92-4bf2-b7e2-4e8bb55dfc2d.htm#GlowAnalyzerProxy) or a S101Logger instance (which can be passed to the S101Client constructor) to write a log file and attach it to your response? 

Thanks!

**Comment by fredrikbergholtz-sr** [comment]
This is the log file I got from creating a logger in my own project:
[s101Log.txt](https://github.com/Lawo/ember-plus-sharp/files/430197/s101Log.txt)

This is the log file I got from running the proxy, pointing it to the Sapphire and running EmberPlusView to look at the proxy: (Interestingly enough, this actually works!)
[20160822_130517_UTC.txt](https://github.com/Lawo/ember-plus-sharp/files/430199/20160822_130517_UTC.txt)

The significant difference, I think is that in my application the get directory query looks like this:
```
  <Event type="Message" timeUtc="13:01:02.73" direction="Send" number="2">
    <Slot>00</Slot>
    <Command>EmberData 01 0A 02</Command>
    <Payload>
      <Root type="RootElementCollection">
        <RootElement type="QualifiedNode">
          <path type="RelativeObjectIdentifier">1</path>
          <children type="ElementCollection">
            <Element type="Command">
              <number type="Integer">32</number>
            </Element>
          </children>
        </RootElement>
      </Root>
    </Payload>
  </Event>
```
while the get directory query from EmberTreeView looks like this:
```
  <Event type="Message" timeUtc="13:05:23.70" direction="Consumer to Provider" number="3">
    <Slot>00</Slot>
    <Command>EmberData 01 1F 02</Command>
    <Payload>
      <Root type="RootElementCollection">
        <RootElement type="Node">
          <number type="Integer">1</number>
          <children type="ElementCollection">
            <Element type="Command">
              <number type="Integer">32</number>
            </Element>
          </children>
        </RootElement>
      </Root>
    </Payload>
  </Event>
```
P.S. Thanks for helping me out with this, I really appreciate it.

**Comment by andreashuber-lawo** [comment]
Hmm, very strange. It looks as if the Sapphire provider does not "understand" qualified nodes. Could you please click "Use Qualified Glow Types" in the Ember+ Viewer application **before** connecting to the Sapphire provider and see whether it still works?

**Comment by fredrikbergholtz-sr** [comment]
I agree, this is really crazy. With the qualified nodes switched on, the query is almost identical to the one from my application, still it works with EmberPlusView via the proxy but not from my application.
```
  <Event type="Message" timeUtc="13:41:47.22" direction="Consumer to Provider" number="3">
    <Slot>00</Slot>
    <Command>EmberData 01 1F 02</Command>
    <Payload>
      <Root type="RootElementCollection">
        <RootElement type="QualifiedNode">
          <path type="RelativeObjectIdentifier">1</path>
          <children type="ElementCollection">
            <Element type="Command">
              <number type="Integer">32</number>
            </Element>
          </children>
        </RootElement>
      </Root>
    </Payload>
  </Event>
```
[20160822_134140_UTC.txt](https://github.com/Lawo/ember-plus-sharp/files/430273/20160822_134140_UTC.txt)

**Comment by andreashuber-lawo** [comment]
Ok, now the only difference seems to be the version number that is sent to the provider. The viewer sends 2.31 while the Ember+ Sharp consumer sends 2.10. The only thing that comes to mind is that the provider deliberately does not respond to 2.10 consumers, but that would be against the spirit of Ember+ (earlier versions are required to simply ignore content of unknown type).

BTW, what port number are you connecting to?

**Comment by andreashuber-lawo** [comment]
Can you please try to connect with the the Ember+ Viewer found in the following old version of the SDK?

https://github.com/Lawo/ember-plus/releases/tag/embersdk-1-2-0

Thanks!

**Comment by fredrikbergholtz-sr** [comment]
That works too. I do get an error message stating:
`Glow Error: Glow DTD version mismatch: found version 2.20, expected 2.10!`
But it still works. In the 1.6.2 viewer I get the corresponding error:
`Glow Error: Glow DTD version mismatch: found version 2.20, expected 2.31!`
But that also works.

**Comment by fredrikbergholtz-sr** [comment]
Wait, I might be lying. Hold on, I need to test this more.

**Comment by andreashuber-lawo** [comment]
Very strange, did you write a log file with Glow Analyzer Proxy?

Thanks!

**Comment by fredrikbergholtz-sr** [comment]
[20160823_122909_UTC.txt](https://github.com/Lawo/ember-plus-sharp/files/432403/20160823_122909_UTC.txt)

**Comment by andreashuber-lawo** [comment]
It's incomprehensible to me why there is no answer from the Sapphire provider. I will try to reproduce this here and get back to you ASAP.

**Comment by fredrikbergholtz-sr** [comment]
Thanks, I appreciate it!

**Comment by andreashuber-lawo** [comment]
Update: I can reproduce this and will check with the Sapphire team why there is no answer. I'll keep you posted.

**Comment by andreashuber-lawo** [comment]
As far as I can tell, this problem should be fixed in the next Sapphire release.

**Comment by fredrikbergholtz-sr** [comment]
Hi, it has been a while but now it is time to awaken my Ember/Sapphire project again.

Have you verified that the library now works with a current version of the Sapphire core?

I still can’t connect. However, I do get a different behavior now with a fresh update of the library itself. This time line 275 in Consumer1.cs throws a TimeOutException just as before, but somehow this gets eaten somewhere and the application simply fails silently.

Best regards
Fredrik Bergholtz
Swedish Radio

Från: Andreas Huber [mailto:notifications@github.com]
Skickat: den 26 augusti 2016 15:25
Till: Lawo/ember-plus-sharp <ember-plus-sharp@noreply.github.com>
Kopia: Fredrik Bergholtz <fredrik.bergholtz@sr.se>; Author <author@noreply.github.com>
Ämne: Re: [Lawo/ember-plus-sharp] Tutorial example fails on real Sapphire mixer (#28)


As far as I can tell, this problem should be fixed in the next Sapphire release.

**Comment by andreashuber-lawo** [comment]
I don't know what the status of the Sapphire SW is. I do know however that they have fixes this in their code base. Did they release a new version in the mean time? If not, this issue will most probably still be present.
